name: Node CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Danger
        run: npm run danger:ci
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
