name: Node CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: install yarn
        run: npm install -g yarn
      - name: Danger
        run: yarn danger ci
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
