name: "Danger JS"
on: [push]

jobs:
  Danger-js:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: danger/danger-js@11.0.7
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
